<!DOCTYPE html>
<html lang="en" ng-app="mercedesApp">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Bill Generation</title>

    <!-- Bootstrap -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-sRIl4kxILFvY47J16cr9ZwB07vP4J8+LH7qKQnuqkuIAvNWLzeN8tE5YBujZqJLB" crossorigin="anonymous">

    <!-- FONTAWESOME -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/7.0.0/css/all.min.css">

    <!-- NASHIE CSS <3 -->
    <link rel="stylesheet" href="../framework/CSS/NashieCss.css">

    <!-- SweetAlert2 -->
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>

    <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.8.3/angular.min.js"></script>
    <script src="../../mercedes_ois/admin/js/LedgerController.js"></script>

</head>

<body class="bg-light" ng-controller="LedgerController" ng-init="VerifySession()">

    <!-- Sidebar -->
    <?php require_once '../framework/Components/mdx_sidebar.php'; ?>
    <!-- Header -->
    <?php require_once '../framework/Components/mdx_header.php'; ?>

    <!-- MAIN CONTENT -->
    <div class="mdx-content" id="mdx_content">
        <div class="container-fluid">
            <div class="col-md-12">
                <!-- Page Bar -->
                <div class="pb-2 mb-3 border-bottom">
                    <span class="fs-12">
                        Administration • Transactions • Bill Generation
                    </span>
                </div>

                <!-- Transaction Form -->
                <div class="row">
                    <!-- Master Search -->
                    <div class="col-md-12 mb-3">
                        <div class="card shadow-sm border-0 rounded-3">
                            <div class="card-body">
                                <h6 class="card-title fw-semibold">Month</h6>
                                <div class="row mb-3">
                                    <!-- <label class="form-label">Accountnumber</label> -->
                                    <div class="col-md-6 d-flex">
                                        <h1>{{ selectedMonthDate | date:'MMMM yyyy' }}</h1>
                                    </div>
                                    <div class="col-md-6 d-flex justify-content-end">
                                        <button class="btn btn-secondary" type="button" ng-click="DoGenerateBill()">
                                            <i class="fa fa-file-excel me-2"></i> Generate Bills
                                        </button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <!-- Transactions -->
                    <div class="col-md-12 mb-3">
                        <div class="card shadow-sm border-0 rounded-3">
                            <div class="card-body">
                                <h6 class="card-title fw-semibold mb-3">Past Generated Months</h6>
                                <!-- Tab Content -->
                                <div class="mt-3" id="transactionTabsContent">
                                    <!-- Latest Transactions -->
                                    <div class="tab-pane fade show active" id="latest" role="tabpanel"
                                        aria-labelledby="latest-tab">
                                        <div class="table-responsive">
                                            <table class="table table-striped table-hover align-middle">
                                                <thead class="table-secondary">
                                                    <tr>
                                                        <th></th>
                                                        <th>Month</th>
                                                        <th>Generated Date</th>
                                                        <th>Generated By</th>
                                                    </tr>
                                                </thead>
                                                <tbody>
                                                    <tr ng-repeat="t in Transactions"
                                                        class="animate__animated animate__fadeIn">
                                                        <td>{{t.transaction_id}}</td>
                                                        <td>{{t.transaction_type}}</td>
                                                        <td>{{t.amount_paid | number: 2}}</td>
                                                    </tr>
                                                    <tr ng-if="!Transactions || Transactions.length === 0">
                                                        <td colspan="5" class="text-center text-muted">No generated
                                                            month
                                                            yet.</td>
                                                    </tr>
                                                </tbody>
                                            </table>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

            </div>

        </div>

        <!-- bootstrap JS -->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-FKyoEForCGlyvwx9Hj09JcYn3nv7wiPVlz7YYwJrWVcXK/BmnVDxM+D2scQbITxI" crossorigin="anonymous">
        </script>

        <script src="../framework/JS/jsForStyling.js"></script>

</body>

</html>